version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: /var/www/html/scripts/restart_httpd.sh
      timeout: 300
      runas: root
