version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
  - source: /restart_httpd.sh
    destination: Scripts/
hooks:
  ApplicationStart:
    - location: Scripts/restart_httpd.sh
      timeout: 300
      runas: root
