version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/index.html
hooks:
  ApplicationStart:
    - location: /root/Scripts/restart_httpd.sh
      timeout: 300
      runas: root
